[package]
name = "app"
version = "0.1.0"
authors = ["Rui Osorio <ruifilipe1708@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libloading = "0.7"
loader = { path = "../loader" }
